import {Perk, PerkType} from "../../modules/characters/pages/CharacterPerks/utils";
import {PerkConnectionModel, Perks} from "../../Models/perks";
import {
    BODY_TIERS
} from "../../modules/characters/pages/CharacterPerks/PerksLayer/lockedSeparator/LockedSeparator.utils";
import tileStyles from './reflex-perks.module.scss';

export const reflexesPerksData: Perk[] = [
    {
        id: Perks.STUNTJOCK,
        tileClassName: tileStyles.Stuntjock,
        type: PerkType.MILESTRONE,
        requiredAttributes: BODY_TIERS.FIRST,
        requiredPerks: [],
        levels: 1,
        connections: [],
        name: "STUNTJOCK",
        description: "Unlocks preem new ways to exit vehicles:\\\\n\\\\nJump out - double-tap [F]\\\\n\\\\nSlide out - hold [F] while at high speed\\\\n\\\\nYou can also draw and fire weapons during these stunts.\\\\n\\\\nWhile driving:\\\\nNo bullet spread penalty from movement\\\\n-50% bullet spread overall"
    },
    {
        id: Perks.MULTITASKER,
        tileClassName: tileStyles.Multitasker,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.FIRST,
        requiredPerks: [Perks.SLIPPERY],
        levels: 1,
        connections: [1],
        name: "MULTITASKER",
        description: "Allows you to shoot while sprinting, sliding and vaulting. "
    },
    {
        id: Perks.PARKOUR,
        tileClassName: tileStyles.Parkour,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.FIRST,
        requiredPerks: [Perks.SLIPPERY],
        levels: 1,
        connections: [2],
        name: "PARKOUR",
        description: "Increased vaulting and climbing speed."
    },
    {
        id: Perks.MUSCLEMEMORY,
        tileClassName: tileStyles.Musclememory,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.FIRST,
        requiredPerks: [Perks.SLIPPERY],
        levels: 1,
        connections: [3],
        name: "MUSCLE MEMORY",
        description: "Allows you to reload weapons while sprinting, sliding and vaulting."
    },
    {
        id: Perks.POWER_SLIDE,
        tileClassName: tileStyles.PowerSlide,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.FIRST,
        requiredPerks: [Perks.SLIPPERY],
        levels: 1,
        connections: [4],
        name: "POWER SLIDE",
        description: "Increased slide distance."
    },
    {
        id: Perks.SLIPPERY,
        tileClassName: tileStyles.Slippery,
        type: PerkType.MILESTRONE,
        requiredAttributes: BODY_TIERS.FIRST,
        requiredPerks: [],
        levels: 1,
        connections: [],
        name: "SLIPPERY",
        description: "The faster you move, the more difficult for enemies to shoot you.\\\\n\\\\nEffect increases when Dashing, dodging, sliding, sprinting and vaulting."
    },

    {
        id: Perks.SPICE_OF_LIFE,
        tileClassName: tileStyles.SpiceOfLife,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.READY_RESTED_RELOADED],
        levels: 1,
        connections: [5],
        name: "SPICE OF LIFE",
        description: "+15% weapon swap speed, –30% bullet spread briefly after swapping weapons. "
    },
    {
        id: Perks.TUNNEL_VISION,
        tileClassName: tileStyles.TunnelVision,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.READY_RESTED_RELOADED],
        levels: 1,
        connections: [15],
        name: "TUNNEL VISION",
        limitationDescription: "Only affects Assault Rifles and SMGs",
        description: "+20% effective range and accuracy."
    },
    {
        id: Perks.MIND_OVER_MATTER,
        tileClassName: tileStyles.MindOverMatter,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.READY_RESTED_RELOADED],
        levels: 1,
        connections: [16],
        name: "MIND OVER MATTER",
        description: "–25% recoil when aiming. "
    },
    {
        id: Perks.READY_RESTED_RELOADED,
        tileClassName: tileStyles.ReadyRestedReloaded,
        type: PerkType.MILESTRONE,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [],
        levels: 1,
        connections: [],
        name: "READY RESTED RELOADED",
        description: "Level 1: –10% stamina cost for shooting with AR and SMGs. \\nLevel 2: +30% reload speed when above 50% stamina.",
        limitationDescription: "Only affects Assault Rifles and SMGs",
    },

    {
        id: Perks.CANT_TOUCH_THIS,
        tileClassName: tileStyles.CantTouchThis,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.DASH],
        levels: 1,
        connections: [8],
        name: "CAN'T TOUCH THIS",
        description: "+100% mitigation chance when performing a Dash. \\n\\nMitigation grants a chance to reduce incoming damage by current Mitigation Strength (default 50%)"
    },
    {
        id: Perks.MAD_DASH,
        tileClassName: tileStyles.MadDash,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.DASH],
        levels: 1,
        connections: [9],
        name: "MAD DASH",
        description: "+100% dash range toward enemies. "
    },
    {
        id: Perks.STEADY_GRIP,
        tileClassName: tileStyles.SteadyGrip,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.DASH],
        levels: 1,
        connections: [17],
        name: "STEADY GRIP",
        description: "Allows you to shoot while Dashing."
    },
    {
        id: Perks.MEAN_STREAK,
        tileClassName: tileStyles.MeanStreak,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.DASH],
        levels: 1,
        connections: [18],
        name: "MEAN STREAK",
        description: "+40% stamina after neutralizing an enemy while dashing. "
    },
    {
        id: Perks.DASH,
        tileClassName: tileStyles.Dash,
        type: PerkType.MILESTRONE,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.SLIPPERY],
        levels: 2,
        connections: [5],
        name: "DASH",
        description: "Level 1: –20% stamina cost for dodging and dashing. \\nLevel 2: Unlocks the ability to Dash.\\\\n\\\\nPress [LCTRL] to perform a Dash.\\\\n\\\\nDashing replaces dodging, allowing you to cover more ground and automatically vault over low obstacles."
    },
    {
        id: Perks.FLASH_AND_THUNDERCLAP,
        tileClassName: tileStyles.FlashAndThunderclap,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.MAD_DASH, Perks.SEEING_DOUBLE],
        levels: 1,
        connections: [11, 12],
        name: "FLASH AND THUNDERCLAP",
        limitationDescription: "Only affects blades",
        description: "When performing Strong Attacks, you now automatically leap to enemies within range. These Leap Attacks can be also performed from midair and deal additional damage that scales with the distance of the leap (max +50%)."
    },
    {
        id: Perks.SEEING_DOUBLE,
        tileClassName: tileStyles.SeeingDouble,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.LEAD_AND_STEEL],
        levels: 1,
        connections: [13],
        name: "SEEING DOUBLE",
        description: "Increased damage and Stun chance with Counterattacks.",
        limitationDescription: "Only affects blades",
    },
    {
        id: Perks.BULLET_DEFLECT,
        tileClassName: tileStyles.BulletDeflect,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.LEAD_AND_STEEL],
        levels: 1,
        connections: [14],
        name: "BULLET DEFLECT",
        limitationDescription: "Only affects blades",
        description: "When your stamina is above 33% blocking projectiles will Deflect them to wherever your reticle is aimed. Well-timed blocking just before being hit increases the damage you deal with deflected bullets. "
    },

    {
        id: Perks.BULLET_TIME,
        tileClassName: tileStyles.BulletTime,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.BULLET_DEFLECT],
        levels: 1,
        // TODO missing connection
        connections: [],
        name: "BULLET TIME",
        limitationDescription: "Only affects blades",
        description: "Whenever time is slowed, Bullet Deflect does not consume Stamina and deflections automatically hit enemies for Crit Damage."
    },

    {
        id: Perks.LEAD_AND_STEEL,
        tileClassName: tileStyles.LeadAndSteel,
        type: PerkType.MILESTRONE,
        requiredAttributes: BODY_TIERS.SECOND,
        requiredPerks: [Perks.SLIPPERY],
        levels: 2,
        connections: [6],
        name: "LEAD AND STEEL",
        limitationDescription: "Only affects blades",
        description: "Level 1: –15% stamina cost for attacks with blades. \\nLevel 2: Unlocks ability to block incoming projectiles with blades. This consumes stamina. "
    },

    {
        id: Perks.SPRAY_AND_PRAY,
        tileClassName: tileStyles.SprayAndPray,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.SHARPSHOOTER],
        levels: 1,
        connections: [22],
        name: "SPRAY AND PRAY",
        limitationDescription: "Only affects Assault Rifles and SMGs",
        description: "–10% Stamina cost for hip-firing. "
    },
    {
        id: Perks.GUN_DANCER,
        tileClassName: tileStyles.GunDancer,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.SHARPSHOOTER],
        levels: 1,
        connections: [23],
        name: "GUN DANCER",
        limitationDescription: "Only affects Assault Rifles and SMGs",
        description: "Aiming no longer slows movement.\\\\n\\\\nAllows you to shoot while vaulting."
    },
    {
        id: Perks.SHOOT_TO_CHILL,
        tileClassName: tileStyles.ShootToChill,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.SHARPSHOOTER],
        levels: 1,
        connections: [28],
        name: "SHOOT TO CHILL",
        limitationDescription: "Only affects Assault Rifles and SMGs",
        description: "+4% Armor penetration for automatic weapons per stack of Sharpshooter."
    },
    {
        id: Perks.PRACTICE_MAKES_PERFECT,
        tileClassName: tileStyles.PracticeMakesPerfect,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.SHARPSHOOTER],
        levels: 1,
        connections: [29],
        name: "PRACTICE MAKES PERFECT",
        limitationDescription: "Only affects Assault Rifles and SMGs",
        description: "+7% Crit Chance and Crit Damage per stack of Sharpshooter."
    },
    {
        id: Perks.SHARPSHOOTER,
        tileClassName: tileStyles.Sharpshooter,
        type: PerkType.MILESTRONE,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.READY_RESTED_RELOADED],
        levels: 3,
        connections: [19],
        name: "SHARPSHOOTER",
        limitationDescription: "Only affects Assault Rifles and SMGs",
        description: "Level 1: +15% aim speed. \\nLevel 2: improved weapon control. \\nLevel 3: each successful shot grants a stack of Sharpshooter. 7% bonus to Stamina Regen Rate and Stamina cost for 2 sec. per stack. Stacks  7 times. New stacks reset duration. All stacks are removed when duration ends."
    },

    {
        id: Perks.AIR_KERENZIKOV,
        tileClassName: tileStyles.AirKerenzikov,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.GUN_DANCER, Perks.AERIAL_ACROBAT],
        levels: 1,
        connections: [24, 25],
        name: "AIR KERENZIKOV",
        limitationDescription: "Only affects Assault Rifles and SMGs",
        description: "Activating Kerenzikov in midair keeps you suspended in the air and extends its duration."
    },
    {
        id: Perks.AERIAL_ACROBAT,
        tileClassName: tileStyles.AerialAcrobat,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.AIR_DASH],
        levels: 1,
        connections: [26],
        name: "AERIAL ACROBAT",
        description: "Improves midair maneuverability."
    },
    {
        id: Perks.AERODYNAMIC,
        tileClassName: tileStyles.Aerodynamic,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.AIR_DASH],
        levels: 1,
        connections: [30],
        name: "AERODYNAMIC",
        description: "+30% Mitigation strength in midair. "
    },
    {
        id: Perks.AIR_DASH,
        tileClassName: tileStyles.AirDash,
        type: PerkType.MILESTRONE,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.DASH],
        levels: 3,
        connections: [20],
        name: "AIR DASH",
        description: "Level 1: –20% dash stamina cost.\\nLevel 2: +20% dash speed. \\nLevel 3: Unlocks the ability to dash in midair. "
    },

    {
        id: Perks.FINISHED_BLADERRUNNER,
        tileClassName: tileStyles.FinishedBladerrunner,
        type: PerkType.MILESTRONE,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.LEAD_AND_STEEL],
        levels: 3,
        connections: [21],
        name: "FINISHER: BLADERRUNNER",
        limitationDescription: "Only affects blades",
        description: "Level 1: -15% Stamina cost for attacks with Blades\\nLevel 2: +20% attack speed with Blades\\nLevel 3: Unlocks a Blade Finisher.\\\\n\\\\nPress [F] when an enemy's Health is low.\\\\n\\\\nRestores 25% Health.",
    },
    {
        id: Perks.FLASH_OF_STEEL,
        tileClassName: tileStyles.FlashOfSteel,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.FINISHED_BLADERRUNNER],
        levels: 1,
        connections: [27],
        name: "FLASH OF STEEL",
        limitationDescription: "Only affects blades",
        description: "+25% movement speed and attack speed for 6 sec. after performing a Finisher"
    },

    {
        id: Perks.OPPORTUNIST,
        tileClassName: tileStyles.Opportunist,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.FINISHED_BLADERRUNNER],
        levels: 1,
        connections: [32],
        name: "OPPORTUNIST",
        limitationDescription: "Only affects blades",
        description: "Enemies affected by Stagger, Stun, Blinding and Bleeding are more susceptible to Finishers."
    },
    {
        id: Perks.GOING_THE_DISTANCE,
        tileClassName: tileStyles.GoingTheDistance,
        type: PerkType.PERK,
        requiredAttributes: BODY_TIERS.THIRD,
        requiredPerks: [Perks.FINISHED_BLADERRUNNER],
        levels: 1,
        connections: [31],
        name: "GOING THE DISTANCE",
        limitationDescription: "Only affects blades",
        description: '+100% Finisher range'
    },

    {
        id: Perks.SALT_IN_THE_WOUND,
        tileClassName: tileStyles.SaltInTheWound,
        type: PerkType.MASTER,
        requiredAttributes: BODY_TIERS.FOURTH,
        requiredPerks: [Perks.SHARPSHOOTER],
        levels: 1,
        connections: [33],
        name: "SALT IN THE WOUND",
        limitationDescription: "Only affects Assault rifles",
        description: "Shooting the same target 7 consecutive times deals bonus damage equal to 100% of the total damage from those shots. "
    },
    {
        id: Perks.SUBMACHINE_FUN,
        tileClassName: tileStyles.SubmachineFun,
        type: PerkType.MASTER,
        requiredAttributes: BODY_TIERS.FOURTH,
        requiredPerks: [Perks.SHARPSHOOTER],
        levels: 1,
        connections: [34],
        name: "SUBMACHINE FUN",
        limitationDescription: "Only affects SMGs",
        description: "Swapping Submachine Guns is faster and automatically reloads them, +22% fire rate after swapping to an SMG. Normal reloading ends the effect. "
    },
    {
        id: Perks.TAILWIND,
        tileClassName: tileStyles.Tailwind,
        type: PerkType.MASTER,
        requiredAttributes: BODY_TIERS.FOURTH,
        requiredPerks: [Perks.AIR_DASH],
        levels: 1,
        connections: [35],
        name: "TAILWIND",
        description: "+25 stamina from performing Air Dashes and double jumps. "
    },
    {
        id: Perks.SLAUGHTERHOUSE,
        tileClassName: tileStyles.Slaughterhouse,
        type: PerkType.MASTER,
        requiredAttributes: BODY_TIERS.FOURTH,
        requiredPerks: [Perks.FINISHED_BLADERRUNNER],
        levels: 1,
        connections: [36],
        name: "SLAUGHTERHOUSE",
        limitationDescription: "Only affects blades",
        description: "All attacks, counterattacks and deflected bullets apply Bleeding, which increases dismemberment chance. Bleeding cannot kill enemies, but does make them more susceptible to Finishers. +25 stamina from dismemberments. "
    },
];

export const reflexConnectionData: PerkConnectionModel[] = [
    {id: 1},
    {id: 2},
    {id: 3},
    {id: 4},
    {id: 5},
    {id: 6},
    {id: 7},

    {id: 8},
    {id: 9},
    {id: 10},
    {id: 11},
    {id: 12},
    {id: 13},
    {id: 14},
    {id: 15},
    {id: 16},
    {id: 17},
    {id: 18},
    {id: 19},
    {id: 20},
    {id: 21},
    {id: 22},
    {id: 23},

    {id: 24},
    {id: 25},
    {id: 26},
    {id: 27},
    {id: 28},
    {id: 29},
    {id: 30},
    {id: 31},
    {id: 32},
    {id: 33},

    {id: 34},
    {id: 35},
    {id: 36},
];