export enum Perks {
    DORPH_HEAD = "DORPH_HEAD",
    COMEBACK_KID = "COMEBACK_KID",
    PAINKILLER = "PAINKILLER",
    SPEED_JUNKIE = "SPEED_JUNKIE",
    ARMY_OF_ONE = "ARMY_OF_ONE",
    FURY_ROAD = "FURY_ROAD"
}