export enum Perks {
    // FIRST TIER
    DORPH_HEAD = "DORPH_HEAD",
    COMEBACK_KID = "COMEBACK_KID",
    PAINKILLER = "PAINKILLER",
    SPEED_JUNKIE = "SPEED_JUNKIE",
    ARMY_OF_ONE = "ARMY_OF_ONE",
    FURY_ROAD = "FURY_ROAD",
    // SECOND TIER
    BULLET_BALLET = 'BULLET_BALLET',
    KINETIC_ABSORPTION = 'KINETIC_ABSORPTION',
    FLY_SWATTER = 'FLY_SWATTER',
    DIE_DIE_DIE = 'DIE_DIE_DIE',
    WRECKING_BALL = 'WRECKING_BALL',
    LIKE_A_FEATHER = 'LIKE_A_FEATHER',
    DONT_STOP_ME_NOW = 'DONT_STOP_ME_NOW',
    BREAKTHROUGH = 'BREAKTHROUGH',
    CLAPBACK = 'CLAPBACK',
    SKULLCRACKER = 'SKULLCRACKER',
    RUSH_OF_BLOOD = 'RUSH_OF_BLOOD',
    JUGGERNAUT = 'JUGGERNAUT',
    CALM_MIND = 'CALM_MIND',
    AFTERSHOCK = 'AFTERSHOCK',
    EPICENTER = 'EPICENTER',
    SPONTANEOUS_OBLITERATION = 'SPONTANEOUS_OBLITERATION',
    ADRENALINE_RUSH = 'ADRENALINE_RUSH',
    QUAKE = 'QUAKE',
    CLOSE_QUARTERS_CARNAGE = 'CLOSE_QUARTERS_CARNAGE',
    DREAD = 'DREAD',
    BLOODLUST = 'BLOODLUST',
    UNSTOPPABLE_FORCE = 'UNSTOPPABLE_FORCE',
    RIPPLE_EFFECT = 'RIPPLE_EFFECT',
    RIP_AND_TEAR = 'RIP_AND_TEAR',
    ONSLAUGHT = 'ONSLAUGHT',
    PAIN_TO_GAIN = 'PAIN_TO_GAIN',
    FINISHER_SAVAGE_SLINGER = 'FINISHER_SAVAGE_SLINGER',
}

export interface PerkConnectionModel {
    id: number
}